[package]
name = "paranoia-launcher"
version = "0.7.6"
description = "Paranoia Client Launcher"
authors = ["Paranoia Team"]
license = "Proprietary"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
sha2 = "0.10"
hex = "0.4"
tauri-plugin-dialog = "2"

[profile.release]
panic = "abort" # Retire le stack trace pour reduire la taille
codegen-units = 1 # Meilleure optimisation, compilation plus longue
lto = true # Link-time optimization (reduit drastiquement la taille)
strip = true # Retire les symboles de debug
opt-level = "s" # Optimise pour la taille ("z" ou "s")
